### ISSUE TITLE
Page cannot show after refresh

### ISSUE THREAD

**Issue by dev-techmoe** [dev-techmoe/filebrowser#2]
Page cannot show after refresh

**Comment by camjac251** [comment]
Is this related to the Share feature? I just found filebrowser and decided to test it out. After uploading a file and sharing the link, I end up stuck with a loading page

**Comment by dev-techmoe** [comment]
> Is this related to the Share feature? I just found filebrowser and decided to test it out. After uploading a file and sharing the link, I end up stuck with a loading page

try [v2.1.1-beta.1](https://github.com/dev-techmoe/filebrowser/releases/tag/v2.1.1-beta.1).  
Waiting for your reply!

**Comment by camjac251** [comment]
That fixed it for me. I was able to load the file page immediately without it hanging on a loading circle.
I have a few feature requests. Can I open some issues for them? Do you have plans for this fork?

edit: just saw the readme on the home page

**Comment by camjac251** [comment]
I was wondering if maybe it would be possible for persistent share links? Like if you move a file into a new folder or rename it, it expires the share link currently. Could it be possible to make permanent ones persistent through moves/renames?

**Comment by dev-techmoe** [comment]
> I was wondering if maybe it would be possible for persistent share links? Like if you move a file into a new folder or rename it, it expires the share link currently. Could it be possible to make permanent ones persistent through moves/renames?

Thank you for your reply. I think it's a little challenging to implement this feature based on the current code after review.  I'm a college student and I have too many tasks to do in my school, so I'm sorry because I can't add any feature at this time. Certainly, PRs are welcome.  Welcome to create issues on there if you find any bugs and I will try to fix them.
